#!/bin/sh -xe
if ! grep -q git@github.com:zulip/zulip.github.io.git .git/config; then
    echo "ERROR: Needs to be run from zulip-org.git working directory"
fi
aws s3 sync ./ s3://zulip.org/ --exclude='.git/*' --exclude=sync-zulip-org
echo "Remember to invalidate the cloudfront cache!"
